spring.application.name=grafos-backend
server.port=8080

# Caminho da biblioteca nativa compilada da logica em C
# O diretorio logica-c gera libgrafo.so (Linux/Mac) ou grafo.dll (Windows)
jna.library.path=${user.dir}/logica-c
