plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.grafos'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'net.java.dev.jna:jna:5.14.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

task compilarLibC(type: Exec) {
    workingDir "${projectDir}/logica-c"
    commandLine 'make', 'all'
    inputs.files fileTree("${projectDir}/logica-c").include('*.c', '*.h', 'Makefile')
    outputs.file "${projectDir}/logica-c/libgrafo.so"
}

bootRun {
    dependsOn compilarLibC
    systemProperty 'jna.library.path', "${projectDir}/logica-c"
}
